# Tutorial2_Extension

Here I try to expand on some of the concepts explored in the tutorial.


# Libraries

In [1]:
"""Necessary libraries"""

# mathematical
import numpy as np

# plotting
import matplotlib.pyplot as plt

# datasets
from sklearn.datasets import make_classification

# modelling
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

"""Setting options"""

# plot styles
plt.style.use('ggplot')

# Gaussian Function

In the tutorial, I created my own gaussian function. However, now I'm interested to expand this for the multivarite case.

Recall that, in the 

In [146]:
# univariate case

def gaussian(x, mu = 0, sigma = 1):
    """
    Gives the cumulative probability for each value in x based on a normal distribution defined by mu and sigma
    
    Parameters:
    -----------
    
    x: np.array OR float
        this is the x values whose cumulative probability is to be found
    
    mu (optional -- defaults to 0): float
        this defines the mean of the normal distribution
    
    sigma (optional -- defaults to 1): float
        this defines the standard deviation of the normal distribution
        
    """
    x = np.asarray(x) if isinstance(x,list) else x
    
    g = 1/(np.sqrt(2*np.pi)* sigma) * np.exp(-1/2 * np.power((x-mu)/sigma,2))
    return g


def multi_gaussian(X, mu = None, Sigma = 1):
    # add option to set the correlation coefficient urself
    n = X.shape[1] # define the degrees of freedom
    
    mu = [0 for i in range(n)] if not mu else mu
    # need to modify mu to be able to add it manually
    
    Sigma = (lambda x: x, lambda x: np.diag(x))[isinstance(Sigma, list)](
        (lambda x: x,lambda x: np.identity(n)*x)[isinstance(Sigma, int)](Sigma)
    )
    
    # this equation is mathematically problematic? You have not scaled the vectors correctly...

    p = 1/((2*np.pi)**(n/2) * np.sqrt(np.linalg.det(Sigma))) * np.exp(
        -1/2 * np.matmul(np.matmul(X-mu, np.linalg.inv(Sigma)), (X-mu).T)
    )
    return p, mu, Sigma

def covariance_matrix(X):
    # this is from tutorial1_extension, needs some modificiation
    """
    Calculates the covariance matrix for a given input X with n = X.shape[1] predictors
    """
    n = X.shape[1]
    n_points = X.shape[0]
    Sigma = np.zeros([n,n])
    mu = [X[:,i].mean(axis = 0) for i in range(n)]
    for i in range(n): # rows
        for j in range(i,n):
            Sigma[i,j] = (X[:,i]*X[:,j]).sum(axis = 0)/n_points - mu[i]*mu[j]
            if i != j:
                Sigma[j,i] = Sigma[i,j]
            
    return mu,Sigma

In [153]:
X = np.array([[2,2],[-3.6,-2]])

mu, Sigma = covariance_matrix(X)

print(multi_gaussian(X, mu = [0,0], Sigma = 1))
X

(array([[2.91502447e-03, 4.30396995e+01],
       [4.30396995e+01, 3.30371766e-05]]), [0, 0], array([[1., 0.],
       [0., 1.]]))


array([[ 2. ,  2. ],
       [-3.6, -2. ]])

In [81]:
n = 3
Sigma = 1
Sigma = (lambda x: x,lambda x: np.asarray(x).reshape(-n,n))[isinstance(Sigma, list)](
     (lambda x: x,lambda x: np.identity(n)*x)[isinstance(Sigma, int)](Sigma)
    )

print(Sigma)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
Sigma = 5
Sigma = (lambda x: x,np.asarray(Sigma).reshape(-n,n))[isinstance(Sigma, list)](
     (lambda x: x,lambda x: 0)[isinstance(Sigma, int)](5)
    )

ValueError: cannot reshape array of size 1 into shape (3)